// Generated by CoffeeScript 1.6.3
(function() {
  var inspect, ps, puts, test_helper, _ref;

  _ref = require('util'), puts = _ref.puts, inspect = _ref.inspect;

  ps = require('../lib');

  test_helper = require('./test_helper');

  describe('Connection', function() {
    beforeEach(function(done) {
      this.schema = 'shard_1234';
      this.client = new test_helper.ClientStub;
      this.pool = new test_helper.PoolStub(this.client);
      this.connection = new ps.Connection(this.pool, this.schema);
      return done();
    });
    it('should be a Connection', function(done) {
      this.connection.should.be.an.instanceOf(ps.Connection);
      return done();
    });
    it('should set search path on client, then send sql query', function(done) {
      var sql,
        _this = this;
      sql = "SELECT * FROM stuffs;";
      return this.connection.query(sql, function(err, result) {
        _this.client.queries[0].should.match(/search_path/);
        _this.client.queries[0].should.include(_this.schema);
        _this.client.queries[1].should.equal(sql);
        return done();
      });
    });
    return it('should acquire AND release client', function(done) {
      var _this = this;
      return this.connection.query("SELECT * FROM stuff;", function(err, result) {
        _this.pool.acquireCount.should.equal(1);
        _this.pool.releaseCount.should.equal(1);
        return done();
      });
    });
  });

}).call(this);
